--- #YAML:1.0
name:               PDL-Graphics-ColorSpace
version:            0.0.7
abstract:           ~
author:
    - Maggie J. Xiong  <maggiexyz+github gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PDL:         2.4.4
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
